name: marlion-internship-portal
region: blr
services:
  - name: student-app
    github:
      repo: Marliontechxr/marlion-internship-portal
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build:student
    run_command: npm run start:student
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    health_check:
      http_path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: "AIzaSyDcOhIcq62aZuh0YVTcjsNdlysCdTYFfjQ"
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: "marlioninternshipportal2025.firebaseapp.com"
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: "marlioninternshipportal2025"
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: "marlioninternshipportal2025.firebasestorage.app"
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: "593947094542"
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: "1:593947094542:web:9ed58b16bcf50ed59d165f"
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        value: "G-CMYEE92CG7"
      - key: NEXT_PUBLIC_APP_URL
        value: "https://internship.marliontech.com"
      - key: DO_AI_API_KEY
        value: "sk-do--LMZmnIi-nmJHmVUJTs3p0RyTkQeArAcfoCdCLtFaXMRnPX-AkgIow7QMC"
      - key: DO_AI_MODEL
        value: "llama3.3-70b-instruct"
